discounts table & model
unchihugo/keylab pull request #50
Opened 2024-12-07 18:13 UTC by aishafh3

2025-02-13 12:13 UTC, michaeltukdev requested changes
This implementation is alright, but it's not the best approach for discounts applied to products within a relationship database. Here are my thoughts:

- Create a separate table to handle which discounts are applied to which products. This would be a junction table such as 'discount_items', and it would contain a foreign key for the product and a foreign key for the discount. This then follows a many-to-many relationship.

2025-03-05 12:33 UTC, unchihugo reviewed
looks good

2025-03-05 20:45 UTC, michaeltukdev requested changes
Hey, this is perfect except for `ApplicableItems string `gorm:"type:text" json:"applicable_items" form:"applicable_items" validate:"omitempty,json"``.

You drop the column so it's no longer needed. 

It would also be good to have a DiscountItem model perhaps? Let me know your thoughts

2025-03-12 06:59 UTC, michaeltukdev approved these changes

2025-03-12 11:49 UTC, merged